import pygame

UPDATE_R2D = pygame.USEREVENT+1
UPDATE_BATTERY = pygame.USEREVENT+2
UPDATE_BATTERY_TEMP = pygame.USEREVENT+3
UPDATE_MOTOR_TEMP = pygame.USEREVENT+4
UPDATE_INVERTER_TEMP = pygame.USEREVENT+5
