import pygame

UPDATE_LOG = pygame.USEREVENT
UPDATE_R2D = pygame.USEREVENT+1
UPDATE_BATTERY = pygame.USEREVENT+2
UPDATE_BATTERY_TEMP = pygame.USEREVENT+3
UPDATE_MOTOR_TEMP = pygame.USEREVENT+4
UPDATE_INVERTER_TEMP = pygame.USEREVENT+5
UPDATE_INVERTER_PCB_TEMP = pygame.USEREVENT+6
UPDATE_CELL_VOLTAGE = pygame.USEREVENT+7
UPDATE_BUS = pygame.USEREVENT+8